server:
  port: 8081
spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.auto_quote_keyword: true
  application:
    name: ApiService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/dessert?characterEncoding=utf8
    username: root
    password: 123456
  sql:
    init:
      encoding: utf8
#      data-locations: classpath:data.sql
      mode: embedded
      continue-on-error: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  profiles:
    include: biz
#server:
#  servlet:
#    context-path: /admin3

#management:
#  endpoints:
#    web:
#      base-path: /actuator  # Actuator的基本路径
#      exposure:
#        include: health
